namespaces:
  - id: 0
    name: default-namespace
  - id: 1
    name: permissions
  - id: 2
    name: roles
  - id: 3
    name: user-roles
  - id: 4
    name: permissions-access
  - id: 5
    name: reports
  - id: 6
    name: groups

dsn: memory

log:
  level: info

limit:
  max_read_depth: 10

serve:
  write:
    host: "0.0.0.0"
    cors:
      allowed_origins:
        - http://localhost
        - http://127.0.0.1
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
    port: 4467
  read:
    host: "0.0.0.0"
    cors:
      allowed_origins:
        - http://localhost
        - http://127.0.0.1
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
    port: 4466